version: '3'
services:
  web:
    build:
      context: .
      dockerfile: DockerfileApache
      args:
        UID_MIN: ${MOVABLETYPE_UID_MIN}
        GID_MIN: ${MOVABLETYPE_GID_MIN}
    ports:
      - "${MOVABLETYPE_WEB_PORT}:80"
    volumes:
      - ./src:/var/www
    depends_on:
      - db
      - mt
    env_file: .env
  mt:
    build:
      context: .
      dockerfile: DockerfileMovableType
      args:
        UID_MIN: ${MOVABLETYPE_UID_MIN}
        GID_MIN: ${MOVABLETYPE_GID_MIN}
        APP_PORT: ${MOVABLETYPE_APP_PORT}
        WORK_DIR: ${MOVABLETYPE_WORK_DIR}
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    env_file: .env
  db:
    image: "mysql:5"
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - my_mt_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: movabletype
      MYSQL_DATABASE: movabletype
      MYSQL_USER: movabletype
      MYSQL_PASSWORD: movabletype
volumes:
  my_mt_data: {}