version: '2'
services:
  web:
    build:
      context: .
      dockerfile: DockerfileApache
      args:
        UID_MIN: ${MOVABLETYPE_UID_MIN}
        GID_MIN: ${MOVABLETYPE_GID_MIN}
    ports:
      - "${MOVABLETYPE_EXTERNAL_PORT}:80"
    volumes:
      - ./src:/var/www
    env_file: .env
  mt:
    build:
      context: .
      dockerfile: DockerfileMovableType
      args:
        UID_MIN: ${MOVABLETYPE_UID_MIN}
        GID_MIN: ${MOVABLETYPE_GID_MIN}
    volumes:
      - ./src:/var/www
    env_file: .env
  db:
    image: "mysql:5"
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: movabletype
      MYSQL_DATABASE: movabletype
      MYSQL_USER: movabletype
      MYSQL_PASSWORD: movabletype